module.exports = {
	zero: require('./zero'),
	one: require('./one'),
	two: require('./two'),
	three: require('./three'),
	four: require('./four'),
	five: require('./five'),
	six: require('./six'),
	seven: require('./seven'),
	eight: require('./eight'),
	nine: require('./nine'),
	s: require('./s'),
	space: require('./space'),
	colon: require('./colon'),
}
